hpc<-read.table("household_power_consumption.txt",header = TRUE,sep=";",na.strings = "?")
newhpc<-subset(hpc,Date=="1/2/2007"|Date=="2/2/2007")
datetime <- strptime(paste(newhpc$Date, newhpc$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
png("Plot4.png")
par(mfrow=c(2,2))
plot(datetime, newhpc$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(datetime,newhpc$Voltage,type="l")
plot(datetime,newhpc$Sub_metering_1,type = "l",xlab="",ylab="Energy sub merging")
lines(datetime,newhpc$Sub_metering_2,type = "l",col="red")
lines(datetime,newhpc$Sub_metering_3,type = "l",col="blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
plot(datetime,newhpc$Global_reactive_power,ylab = "Global_reactive_power",type="l")
dev.off()